hydra:
  run:
    dir: ${oc.env:SCRATCH,.}/jaxmarl/outputs/ippo_cnn_overcooked/${now:%Y-%m-%d}/${now:%H-%M-%S}

"LR": 0.0005
"NUM_ENVS": 2048
"NUM_STEPS": 256
"TOTAL_TIMESTEPS": 1e7
"UPDATE_EPOCHS": 4
"NUM_MINIBATCHES": 16
"GAMMA": 0.99
"GAE_LAMBDA": 0.95
"CLIP_EPS": 0.2
"ENT_COEF": 0.01
"VF_COEF": 0.5
"MAX_GRAD_NORM": 0.5
"ACTIVATION": "relu"
"ENV_NAME": "overcooked"
"REW_SHAPING_HORIZON": 5e6 # for how many timesteps add a shaping reward
"ENV_KWARGS": 
  "layout" : "counter_circuit"
"ANNEAL_LR": True
"SEED": 30
"NUM_SEEDS": 1
"TUNE": True
"CARBS_NUM_TRIALS": 50

# WandB Params
"ENTITY": ""
"PROJECT": "ippo_cnn_overcookedv1"
"WANDB_MODE" : "offline"
