hydra:
  run:
    dir: ${oc.env:SCRATCH,.}/jaxmarl/outputs/ippo_rnn_overcooked_v3/${now:%Y-%m-%d}/${now:%H-%M-%S}

"ENV_KWARGS":
  "layout": "cramped_room"
  "agent_view_size": 2
  "shaped_rewards": True
  "random_agent_positions": True
  "max_steps": 400

"LR": 0.00025
"ANNEAL_LR": True
"LR_WARMUP": 0.05

"NUM_ENVS": 256
"NUM_STEPS": 256
"UPDATE_EPOCHS": 4
"NUM_MINIBATCHES": 64

"TOTAL_TIMESTEPS": 3e7
"REW_SHAPING_HORIZON": 1.5e7

"FC_DIM_SIZE": 128
"GRU_HIDDEN_DIM": 128

"CLIP_EPS": 0.2
"ENT_COEF": 0.01
"GAMMA": 0.99
"GAE_LAMBDA": 0.95
"VF_COEF": 0.5
"MAX_GRAD_NORM": 0.25
"ACTIVATION": "relu"
"SEED": 0
"NUM_SEEDS": 1

"ENTITY": ""
"PROJECT": ""
"WANDB_MODE": "disabled"
"WANDB_DIR": "${oc.env:SCRATCH,.}/jaxmarl/ippo_overcooked_v3"
"USE_RICH_MONITOR": True

