"TOTAL_TIMESTEPS": 2e6
"NUM_ENVS": 32
"NUM_STEPS": 16
"BUFFER_SIZE": 1e6
"BUFFER_BATCH_SIZE": 1024
"ACTOR_HIDDEN_SIZE": 64
"CRITIC_HIDDEN_SIZE": 64
"NUM_LAYERS": 2
"ACTOR_LR": 0.01
"CRITIC_LR": 0.01
"MAX_GRAD_NORM": 0.5
"TARGET_UPDATE_INTERVAL": 1
"TAU": 0.01
"NUM_EPOCHS": 1
"GAMMA": 0.95
"LEARNING_STARTS": 10000
"NOISE_STD": 0.1
"NOISE_CLIP": 0.5
"ACTION_REG": 0.001

# ENV
"ENV_NAME": "MPE_simple_spread_v3"
"ENV_KWARGS":
  action_type: "Continuous"

# evaluate
"TEST_DURING_TRAINING": True
"TEST_INTERVAL": 0.05 # as a fraction of updates
"TEST_NUM_STEPS": 30
"TEST_NUM_ENVS": 512

"ALG_NAME": "maddpg_ff"
